# This is a basic workflow that is manually triggered

name: Test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  # Enable manual run
  workflow_dispatch:
    inputs:      
      id:
        description: "ID"
        required: true
        default: "123da"
        type: string
      resulation:
        description: "Resulation"
        required: true
        default: "360p"
        type: string
      resulation-id:
        description: "Resulation ID"
        required: true
        default: "1"
        type: string

jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
    
    # Setup Java environment in order to build the Android app.
    - uses: actions/checkout@v3.0.2
    
    - run: sudo apt install ffmpeg
    - run: npm install
    - run: npm run build:linux
    - run: npm link
    - run: echo "${{ secrets.TOKEN }}" >> token
    - run: printf '${{ github.event.inputs.resulation-id }}\n' | filimo-plus-cli ${{ github.event.inputs.id }}
    - run: ffmpeg -i "./movie/${{ github.event.inputs.id }}/${{ github.event.inputs.resulation }}/${{ github.event.inputs.id }}.mp4" -i "./movie/${{ github.event.inputs.id }}/${{ github.event.inputs.resulation }}/${{ github.event.inputs.id }}.srt" -map 0:0 -map 0:1 -map 1:0 -c:v copy -c:a copy -c:s mov_text ${{ github.event.inputs.id }}_sub.mp4
    - run: ls
    - uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: Video
        document: './movie/${{ github.event.inputs.id }}/${{ github.event.inputs.resulation }}/${{ github.event.inputs.id }}.mp4'
    - uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: With Sub
        document: './${{ github.event.inputs.id }}_sub.mp4'
    - uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: Subtitle
        document: './movie/${{ github.event.inputs.id }}/${{ github.event.inputs.resulation }}/${{ github.event.inputs.id }}.srt'
    - uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: Subtitle - EN
        document: './movie/${{ github.event.inputs.id }}/${{ github.event.inputs.resulation }}/${{ github.event.inputs.id }}_en.srt'
